export const CREATE_ENTRY_SUCCESS = 'CREATE_ENTRY_SUCCESS';
export const DELETE_ENTRY_SUCCESS = 'DELETE_ENTRY_SUCCESS';
export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS';
export const FETCH_ENTRY_SUCCESS = 'FETCH_ENTRY_SUCCESS';
export const FETCH_ENTRY_CHILDREN_SUCCESS = 'FETCH_ENTRY_CHILDREN_SUCCESS';
export const FETCH_OTHER_ENTRIES = 'FETCH_OTHER_ENTRIES';
export const GET_PAGE_ID_SUCCESS = 'GET_PAGE_ID_SUCCESS';
export const LIKE_ENTRY_FAILURE = 'LIKE_ENTRY_FAILURE';
export const LIKE_ENTRY_SUCCESS = 'LIKE_ENTRY_SUCCESS';
export const REMOVE_BRAND_NEW = 'REMOVE_BRAND_NEW';
export const RESET_ERRORS = 'RESET_ERRORS';
export const SEARCH_ENTRIES_SUCCESS = 'SEARCH_ENTRIES_SUCCESS';
export const SELECT_REPLY_ENTRY = 'SELECT_REPLY_ENTRY';
export const SITE_ID_REQUEST = 'SITE_ID_REQUEST';
export const SITE_ID_SUCCESS = 'SITE_ID_SUCCESS';

export const SEARCH_ALL_SUCCESS = 'SEARCH_ALL_SUCCESS';
