export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILURE = 'FOLLOW_USER_FAILURE';

export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAILURE = 'UNFOLLOW_USER_FAILURE';

export const GET_MY_FOLLOWERS_REQUEST = 'GET_MY_FOLLOWERS_REQUEST';
export const GET_MY_FOLLOWERS_SUCCESS = 'GET_MY_FOLLOWERS_SUCCESS';
export const GET_MY_FOLLOWERS_FAILURE = 'GET_MY_FOLLOWERS_FAILURE';

export const GET_MY_FOLLOWINGS_REQUEST = 'GET_MY_FOLLOWINGS_REQUEST';
export const GET_MY_FOLLOWINGS_SUCCESS = 'GET_MY_FOLLOWINGS_SUCCESS';
export const GET_MY_FOLLOWINGS_FAILURE = 'GET_MY_FOLLOWINGS_FAILURE';

export const GET_USER_FOLLOWERS_REQUEST = 'GET_USER_FOLLOWERS_REQUEST';
export const GET_USER_FOLLOWERS_SUCCESS = 'GET_USER_FOLLOWERS_SUCCESS';

export const GET_USER_FOLLOWINGS_REQUEST = 'GET_USER_FOLLOWINGS_REQUEST';
export const GET_USER_FOLLOWINGS_SUCCESS = 'GET_USER_FOLLOWINGS_SUCCESS';
