export const UPDATE_SUBSCRIPTION = "UPDATE_SUBSCRIPTION";
export const GET_SUBSCRIPTIONS_REQUEST = "GET_SUBSCRIPTIONS_REQUEST";
export const GET_SUBSCRIPTIONS_SUCCESS = "GET_SUBSCRIPTIONS_SUCCESS";
export const SUBSCRIBE_SUCCESS = "SUBSCRIBE_SUCCESS";
export const GET_TRENDING_FROM_NETWORK_SUCCESS =
  "GET_TRENDING_FROM_NETWORK_SUCCESS";
