export const GET_ME_REQUEST = 'GET_ME_REQUEST';
export const GET_ME_SUCCESS = 'GET_ME_SUCCESS';
export const GET_ME_FAILURE = 'GET_ME_FAILURE';
export const GET_MY_HISTORY_SUCCESS = 'GET_MY_HISTORY_SUCCESS';

export const UPDATE_ME_SUCCESS = 'UPDATE_ME_SUCCESS';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const REMOVE_ERRORS = 'REMOVE_ERRORS';

export const DIFFERENT_NEW_PASSWORDS = 'DIFFERENT_NEW_PASSWORDS';

export const THEME_CHANGED = 'THEME_CHANGED';
export const UPLOAD_NEW_PROFILE_PICTURE = 'UPLOAD_NEW_PROFILE_PICTURE';

export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
