platform :ios, '9.0'

target 'mobile' do
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'Firebase/Core'
  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

end
